# Generated by the release workflow. Do not edit by hand.
class Oberth < Formula
  desc "Self-hosted CI that runs a pipeline before it reaches the forge"
  homepage "https://github.com/Nikitzu/oberth"
  version "0.13.27-poc13"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Nikitzu/oberth/releases/download/v0.13.27-poc13/oberth-darwin-arm64"
      sha256 "f14f240b7c5193640dc7ce9f061f5c43106bba0571cdc147d3853f5b9e0f9a12"
    end
    on_intel do
      url "https://github.com/Nikitzu/oberth/releases/download/v0.13.27-poc13/oberth-darwin-amd64"
      sha256 "03f31ffa4543e8d385be329afda3bb0ecb873d433cd10111c757b2bb54031314"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Nikitzu/oberth/releases/download/v0.13.27-poc13/oberth-linux-arm64"
      sha256 "5f0fd128fa73282cff6758a2b8fff4da356d2bf71f5cd7dd3f71caaa4e41d77d"
    end
    on_intel do
      url "https://github.com/Nikitzu/oberth/releases/download/v0.13.27-poc13/oberth-linux-amd64"
      sha256 "cf7fc4799bc4f34fa3f6f5e6e01c159a0e4881880aadae4689825fa89d3e0766"
    end
  end

  def install
    bin.install Dir["oberth-*"].first => "oberth"
  end

  test do
    assert_match "oberth", shell_output("#{bin}/oberth version")
  end
end
