# Generated by the release workflow. Do not edit by hand.
class Oberth < Formula
  desc "Self-hosted CI that runs a pipeline before it reaches the forge"
  homepage "https://github.com/Nikitzu/oberth"
  version "0.13.27-poc16"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Nikitzu/oberth/releases/download/v0.13.27-poc16/oberth-darwin-arm64"
      sha256 "ac74d7635efd781a466e71f629c625665b8cda02e8a7e671107982b6730bfa74"
    end
    on_intel do
      url "https://github.com/Nikitzu/oberth/releases/download/v0.13.27-poc16/oberth-darwin-amd64"
      sha256 "75683491d9922a1b79327e17e7c14acd9cedb4ade8d1e4535bc5c4fe23135536"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Nikitzu/oberth/releases/download/v0.13.27-poc16/oberth-linux-arm64"
      sha256 "ba81c413c0a1523a0584af2a6fc65cc15934468aeeeb5f69a475af79338c5ad8"
    end
    on_intel do
      url "https://github.com/Nikitzu/oberth/releases/download/v0.13.27-poc16/oberth-linux-amd64"
      sha256 "7e601cd4700b3287244c98ff16f3bc238e8f96b534de6f0f347a723eca273daf"
    end
  end

  def install
    bin.install Dir["oberth-*"].first => "oberth"
  end

  test do
    assert_match "oberth", shell_output("#{bin}/oberth version")
  end
end
