# Generated by the release workflow. Do not edit by hand.
class Oberth < Formula
  desc "Self-hosted CI that runs a pipeline before it reaches the forge"
  homepage "https://github.com/Nikitzu/oberth"
  version "0.13.27-poc7"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/Nikitzu/oberth/releases/download/v0.13.27-poc7/oberth-darwin-arm64"
      sha256 "3bb3bfa536db3d11fb77d8d19c4cf06cc0a4766da3f6b9e49b5e5fb48ba400cc"
    end
    on_intel do
      url "https://github.com/Nikitzu/oberth/releases/download/v0.13.27-poc7/oberth-darwin-amd64"
      sha256 "db4828288c093b9205f6ad1155b58f98232bafec25f1cdf0f68d3a39acf7560a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Nikitzu/oberth/releases/download/v0.13.27-poc7/oberth-linux-arm64"
      sha256 "96aad07ce016dd7db16f972c5717b81aad29f7e8964b9b3214f8658baf848bd3"
    end
    on_intel do
      url "https://github.com/Nikitzu/oberth/releases/download/v0.13.27-poc7/oberth-linux-amd64"
      sha256 "145caea1adbd065b453e924ee4e9d2b72cdeb714025320faf1edcde49a432f53"
    end
  end

  def install
    bin.install Dir["oberth-*"].first => "oberth"
  end

  test do
    assert_match "oberth", shell_output("#{bin}/oberth version")
  end
end
